version: {build}
image: Visual Studio 2017
branches:
  only:
  - master
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true
init:
  - cmd: git config --global core.autocrlf true
build_script:
  - ps: .\build.ps1
test: off
artifacts:
- path: .\src\Xaki\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/mehalick/api/v2/package
  api_key:
    secure: IGG9TOzkfdC0AqFl8XS+0s2IjS6bgIhuH24JnQjEyThMXPw7SU9Glk9a84BgR3vc
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  skip_symbols: true
  api_key:
    secure: t3blEIQiDIYjjWhOSTTtrcAnzJkmSi+0zYPxC1v4RDzm6oI/gIpD6ZtrOGsYu2jE
  on:
    appveyor_repo_tag: true